<template>
<div class="container">
    <div class="content">
     <div class="container"> 
         <div class="box">
           <div class="field is-grouped">
  <p class="control">
    <a class="button">
       <i class="far fa-play-circle"></i>
        <b>PLAY</b>
    </a>
  </p>
  <p class="control">
    <a class="button">
      <i class="far fa-pause-circle"></i>
      <b>PAUSE</b>
    </a>
  </p>
  <p class="control">
    <a class="button">
      <i class="fas fa-redo-alt"></i>
      <b>RERUN</b>
    </a>
  </p>
</div>
          
         </div>
       </div>
    </div>
  </div>
</template>

<script>
    export default {
        data () {
            
        },
  }
    }
</script>

<style>

</style>